[en]
  languageName = "English"
  weight = 1

[nl]
  languageName = "Nederlands"
  weight = 7
  [fr.params]
    description = "Een extreem snel, responsief en feature-rijk blogthema voor Hugo"
    keywords = "Hugo, Bootstrap, Theme Blog"

[fr]
  languageName = "Français"
  weight = 2
  [fr.params]
    description = "Un thème de blog extrêmement rapide, réactif et riche en fonctionnalités pour Hugo"
    keywords = "Hugo, Bootstrap, Thème Blog"

[zh-hans]
  languageName = "简体中文"
  weight = 4
  [zh-hans.params]
    description = "一个快速、响应式和功能丰富的 Hugo 博客主题"
    keywords = "Hugo, Bootstrap, 博客主题"
    [zh-hans.params.archive]
      dateFormat = "01-02"

[zh-hant]
  languageName = "繁體中文"
  weight = 5
  [zh-hant.params]
    description = "一個快速、響應式和功能豐富的 Hugo 博客主題"
    keywords = "Hugo, Bootstrap, 博客主題"
    [zh-hant.params.archive]
      dateFormat = "01-02"

[ar]
  languageName = "العربية"
  LanguageDirection = 'rtl'
  weight = 3
  [ar.params]
    description = "ثيم مدونة مصمم لـ هوجو سريع وغني بالميزات"

[ja]
  languageName = "日本語"
  weight = 6
  [ja.params]
    description = "Hugo向けにカスタマイズされた非常に高速で応答性の高い、機能豊富なブログテーマ"
    keywords = "Hugo, Bootstrap, ブログテーマ"
    [ja.params.archive]
      dateFormat = "1/2"
